export const PUSH_TIMELINE = 'PUSH_TIMELINE'
export const CLICKED_TWEET = 'CLICKED_TWEET'
export const INCREMENTS_TIMELINE_CURRENT_INDEX = 'INCREMENTS_TIMELINE_CURRENT_INDEX'

export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const FAVORITE = 'FAVORITE'
export const RETWEET = 'RETWEET'
export const DELETE_TWEET = 'DELETE_TWEET'

export const UPDATE_STATUS = 'UPDATE_STATUS'
export const UPDATE_INPUT = 'UPDATE_INPUT'
export const CLEAR_INPUT = 'CLEAR_INPUT'
export const REPLY = 'REPLY'

export const ATTACH_CONTENTS = 'ATTACH_CONTENTS'
export const DELETE_CONTENTS = 'DELETE_CONTENTS'
