export const PUSH_TIMELINE = 'PUSH_TIMELINE'
export const CLICKED_TWEET = 'CLICKED_TWEET'
export const INCREMENTS_TIMELINE_CURRENT_INDEX = 'INCREMENTS_TIMELINE_CURRENT_INDEX'

export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const FAVORITE = 'FAVORITE'
export const RETWEET = 'RETWEET'
