export const PUSH_TIMELINE = 'PUSH_TIMELINE'
export const CLICKED_TWEET = 'CLICKED_TWEET'
export const INCREMENTS_TIMELINE_CURRENT_INDEX = 'INCREMENTS_TIMELINE_CURRENT_INDEX'
export const CLICKED_RETWEET_BUTTON = 'CLICKED_RETWEET_BUTTON'
export const CLICKED_FAVORITE_BUTTON = 'CLICKED_FAVORITE_BUTTON'

export const ADD_ACCOUNT = 'ADD_ACCOUNT'
